# Generated by Django 5.2.4 on 2025-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите стоимость товара",
                max_length=100,
                null=True,
                verbose_name="Стоимость товара",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID товара",
                max_length=255,
                null=True,
                verbose_name="ID товара",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=100,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
